dist: xenial
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
addons:
  apt:
    packages:
      - google-chrome-stable
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3
install:
  - npm install
script:
  - npm run test
after_success:
  - bash <(curl -s https://codecov.io/bash)
